Repository PegaSysEng/pantheon, pull requests merged in 2018-12, with the labels that each got.

#346 added --nodes-whitelist param to CLI and NodeWhitelistController
  ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/PermissioningConfiguration.java
  ethereum/core/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/PermissioningConfigurationTest.java
  pantheon/src/main/java/tech/pegasys/pantheon/Runner.java
  pantheon/src/main/java/tech/pegasys/pantheon/RunnerBuilder.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/controller/NodeWhitelistController.java
  pantheon/src/test/java/tech/pegasys/pantheon/RunnerTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
Labels: enhancement, permissioning

#323 [NC-1856] Extracted non-Docker CLI parameters to picoCLI mixin.
  pantheon/src/main/java/tech/pegasys/pantheon/cli/DefaultCommandValues.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/StandaloneCommand.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
Labels: enhancement

#344 Plumb in three more metrics
  acceptance-tests/build.gradle
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/ThreadPantheonNodeRunner.java
  ethereum/core/build.gradle
  ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/db/DefaultMutableBlockchain.java
  ethereum/core/src/test-support/java/tech/pegasys/pantheon/ethereum/core/ExecutionContextTestFixture.java
  ethereum/core/src/test-support/java/tech/pegasys/pantheon/ethereum/core/InMemoryStorageProvider.java
  ethereum/core/src/test/java/tech/pegasys/pantheon/ethereum/db/DefaultMutableBlockchainTest.java
  ethereum/core/src/test/java/tech/pegasys/pantheon/ethereum/db/GenesisBlockMismatchTest.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/BlockPropagationManager.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/DefaultSynchronizer.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/sync/BlockPropagationManagerTest.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/PeerDiscoveryAgentTest.java
  metrics/src/main/java/tech/pegasys/pantheon/metrics/MetricCategory.java
  metrics/src/main/java/tech/pegasys/pantheon/metrics/OperationTimer.java
  metrics/src/main/java/tech/pegasys/pantheon/metrics/noop/NoOpMetricsSystem.java
  pantheon/src/main/java/tech/pegasys/pantheon/RunnerBuilder.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonControllerBuilder.java
  pantheon/src/main/java/tech/pegasys/pantheon/controller/CliquePantheonController.java
  pantheon/src/main/java/tech/pegasys/pantheon/controller/IbftLegacyPantheonController.java
  pantheon/src/main/java/tech/pegasys/pantheon/controller/IbftPantheonController.java
  pantheon/src/main/java/tech/pegasys/pantheon/controller/MainnetPantheonController.java
  pantheon/src/main/java/tech/pegasys/pantheon/controller/PantheonController.java
  pantheon/src/test/java/tech/pegasys/pantheon/RunnerTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/util/BlockImporterTest.java
Labels: enhancement

#337 NC-1880 High TX volume swamps block processing
  consensus/ibftlegacy/src/main/java/tech/pegasys/pantheon/consensus/ibftlegacy/protocol/Istanbul64ProtocolManager.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/manager/AbstractEthTask.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/manager/EthProtocolManager.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/manager/EthScheduler.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/BlockPropagationManager.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/SynchronizerConfiguration.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionSender.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionsMessageHandler.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/DeterministicEthScheduler.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/EthProtocolManagerTest.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/EthSchedulerTest.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/transactions/TestNode.java
  pantheon/src/main/java/tech/pegasys/pantheon/controller/CliquePantheonController.java
  pantheon/src/main/java/tech/pegasys/pantheon/controller/IbftLegacyPantheonController.java
  pantheon/src/main/java/tech/pegasys/pantheon/controller/IbftPantheonController.java
  pantheon/src/main/java/tech/pegasys/pantheon/controller/MainnetPantheonController.java
Labels: bug

#342 Added Coding Conventions
  CODING-CONVENTIONS.md
  CONTRIBUTING.md
  README.md
Labels: enhancement

#295 [NC-1742] Added host whitelist for Json-RPC.
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/PantheonNodeFactory.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcConfiguration.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpService.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpServiceHostWhitelistTest.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpServiceRpcApisTest.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpServiceTest.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/custom/JsonRPCWhitelistHostsProperty.java
  pantheon/src/test/java/tech/pegasys/pantheon/RunnerTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  quickstart/src/test/java/tech/pegasys/pantheon/tests/quickstart/DockerQuickstartTest.java
Labels: enhancement, security

#268 [NC-875] Implement iterative peer search
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerDistanceCalculator.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerTable.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/RecursivePeerRefreshState.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerDiscoveryControllerDistanceCalculatorTest.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/RecursivePeerRefreshStateTest.java
  ethereum/p2p/src/test/resources/peers.json
Labels: enhancement

#437 text change
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
Labels: permissioning

#381 Doc migration
  .gitattributes
  docs/Configuring-Pantheon/Accounts-for-Testing.md
  docs/Configuring-Pantheon/Logging.md
  docs/Configuring-Pantheon/NetworkID-And-ChainID.md
  docs/Configuring-Pantheon/Networking.md
  docs/Configuring-Pantheon/Node-Keys.md
  docs/Configuring-Pantheon/Passing-JVM-Options.md
  docs/Configuring-Pantheon/Proof-of-Authority.md
  docs/Configuring-Pantheon/Testing-Developing-Nodes.md
  docs/Getting-Started/ExplorerBlockDetails.png
  docs/Getting-Started/ExplorerSearch.png
  docs/Getting-Started/ExplorerSummary.png
  docs/Getting-Started/Getting-Started.md
  docs/Getting-Started/Private-Network-Quickstart.md
  docs/Getting-Started/Run-Docker-Image.md
  docs/Getting-Started/Starting-Pantheon.md
  docs/GettingStartedBinaries.md
  docs/Installation/Build-From-Source.md
  docs/Installation/Install-Binaries.md
  docs/Installation/Install-Chocolatey.md
  docs/Installation/Overview.md
  docs/Reference/JSON-RPC-API-Methods.md
  docs/Reference/JSON-RPC-API-Objects.md
  docs/Reference/JSON-RPC-API.md
  docs/Reference/Pantheon-CLI-Syntax.md
  docs/Reference/Using-JSON-RPC-API.md
  docs/Using-Pantheon/Account-Management.md
  docs/Using-Pantheon/Debugging.md
  docs/Using-Pantheon/FilterExample.md
  docs/Using-Pantheon/Filters.md
  docs/Using-Pantheon/Mining.md
  docs/Using-Pantheon/RPC-PubSub.md
  docs/Using-Pantheon/Switching from Geth.md
  docs/Using-Pantheon/Transactions.md
  docs/community/code-reviews.md
  docs/community/community-membership.md
  docs/conf.py
  docs/custom_theme/404.html
  docs/custom_theme/favicon.ico
  docs/custom_theme/partials/footer.html
  docs/custom_theme/partials/toc.html
  docs/development/code-coverage.md
  docs/development/running-with-gradle.md
  docs/global/test_accounts.md
  docs/index.md
  docs/requirements.txt
  mkdocs.yml
Labels: documentation, enhancement

#439 Added Goerli
  docs/index.md
Labels: documentation

#443 Fix #442 add line numbers on long JS and remove useless extension
  mkdocs.yml
Labels: documentation

#471 Add Google analytics to doc site
  docs/custom_theme/assets/stylesheets/pantheon_custom.css
  docs/custom_theme/main.html
  docs/custom_theme/partials/footer.html
  mkdocs.yml
Labels: documentation, enhancement

#484 Merging changes made to Wiki post migration
  docs/Getting-Started/Private-Network-Quickstart.md
  docs/Getting-Started/Starting-Pantheon.md
  docs/Installation/Install-Chocolatey.md
  docs/Reference/JSON-RPC-API-Methods.md
  docs/Reference/JSON-RPC-API-Objects.md
  docs/Reference/Pantheon-CLI-Syntax.md
  docs/Reference/Using-JSON-RPC-API.md
  docs/Using-Pantheon/RPC-PubSub.md
Labels: documentation

#479 Fixes the GA scripts
  docs/custom_theme/main.html
  mkdocs.yml
Labels: documentation
