Repository PegaSysEng/pantheon, pull requests merged in 2019-06, with the labels that each got.

#1519 [PAN-2547] Modified JSON-RPC subscription processing to avoid blockin…
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/SubscriptionManager.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/blockheaders/NewBlockHeadersSubscriptionService.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/syncing/SyncingSubscriptionService.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/blockheaders/NewBlockHeadersSubscriptionServiceTest.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/subscription/syncing/SyncingSubscriptionServiceTest.java
Labels: WIP

#1533 update and fix example scripts doc page and mkdocs
  MKDOCS-MARKDOWN-GUIDE.md
  docs/Using-Pantheon/Transactions/Transactions.md
  docs/Using-Pantheon/Transactions/scripts/.gitignore
  docs/Using-Pantheon/Transactions/scripts/create_contract_raw_transaction.js
  docs/Using-Pantheon/Transactions/scripts/create_value_raw_transaction.js
  docs/Using-Pantheon/Transactions/scripts/package.json
  docs/requirements.txt
Labels: documentation

#1511 [PIE-1602] Implement operator tool. (blockchain network configuration for permisionned networks)
  config/src/main/java/tech/pegasys/pantheon/config/JsonGenesisConfigOptions.java
  consensus/ibft/src/main/java/tech/pegasys/pantheon/consensus/ibft/IbftExtraData.java
  gradle/versions.gradle
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/operator/OperatorSubCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/rlp/IbftExtraDataCLIAdapter.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/operator/OperatorSubCommandTest.java
  pantheon/src/test/resources/operator/config_generate_keys.json
  pantheon/src/test/resources/operator/config_import_keys.json
Labels: api, continuous-integration, enhancement, permissioning, testing

#1539 Update ethstats doc
  docs/Alethio/Lite-Block-Explorer.md
  docs/Alethio/Lite-Network-Monitor.md
  docs/Alethio/Overview.md
Labels: documentation

#1553 [PIE-1612] [PIE-1613] liveness and readiness probe stub endpoints
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpService.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/health/HealthService.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/health/LivenessService.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/health/ReadinessService.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpServiceTest.java
  pantheon/src/main/java/tech/pegasys/pantheon/RunnerBuilder.java
Labels: api, continuous-integration, docker, enhancement

#1554 Reorganise monitoring docs
  docs/Configuring-Pantheon/Networking/Configuring-Ports.md
  docs/Monitoring/Alethio/Lite-Block-Explorer.md
  docs/Monitoring/Alethio/Lite-Network-Monitor.md
  docs/Monitoring/Alethio/Overview.md
  docs/Monitoring/Alethio/ethstats.png
  docs/Monitoring/Alethio/explorer.png
  docs/Monitoring/Monitoring-Performances.md
  docs/Reference/Pantheon-CLI-Syntax.md
  mkdocs.yml
Labels: documentation

#1570 [PAN-2799] Added generate-blockchain-config
  docs/Reference/Pantheon-CLI-Syntax.md
  docs/Tutorials/Create-IBFT-Network.md
Labels: documentation

#1588 add quotes around asterisks params to prevent shell expansion
  docs/Getting-Started/Starting-Pantheon.md
  docs/Monitoring/Alethio/Lite-Block-Explorer.md
  docs/Pantheon-API/Pantheon-API.md
  docs/Privacy/Configuring-Privacy.md
  docs/Reference/Pantheon-CLI-Syntax.md
  docs/Tutorials/Create-IBFT-Network.md
  docs/Tutorials/Create-Permissioned-Network.md
  docs/Tutorials/Create-Private-Clique-Network.md
  docs/Tutorials/Create-Private-Network.md
Labels: documentation

#1609 [PIE-1709] Implement Prometheus metric counter for skipped expired transaction messages.
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionPoolFactory.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionsMessageProcessor.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionsMessageProcessorTest.java
  metrics/core/src/main/java/tech/pegasys/pantheon/metrics/RunnableCounter.java
Labels: enhancement, performance

#1610 [PIE-1710] Expose a CLI option to configure the life time of transaction messages.
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionPool.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionPoolFactory.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionsMessageHandler.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/EthProtocolManagerTest.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/transactions/TestNode.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/controller/PantheonControllerBuilder.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/resources/everything_config.toml
Labels: api, enhancement

#1615 [PAN-2850] Create a transaction pool configuration object
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/ThreadPantheonNodeRunner.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionPoolConfiguration.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionPoolFactory.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/EthProtocolManagerTest.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/transactions/TestNode.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/controller/PantheonControllerBuilder.java
  pantheon/src/test/java/tech/pegasys/pantheon/PrivacyTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/RunnerTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/util/BlockImporterTest.java
Labels: api, enhancement

#1616 [PIE-1723] Cache TransactionValidationParams instead of creating new object for each call
  ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/mainnet/TransactionValidationParams.java
  ethereum/core/src/test/java/tech/pegasys/pantheon/ethereum/mainnet/TransactionValidationParamsTest.java
Labels: performance, testing
