Repository PegaSysEng/pantheon, pull requests merged in 2019-01, with the labels that each got.

#487 Acc whitelist api
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/AcceptanceTestBase.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/account/Account.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/condition/eth/ExpectEthSendRawTransactionException.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/condition/perm/AddAccountsToWhitelistSuccessfully.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/condition/perm/GetExpectedAccountsWhitelist.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/condition/perm/RemoveAccountsFromWhitelistSuccessfully.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/jsonrpc/Eth.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/jsonrpc/Perm.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/ProcessPantheonNodeRunner.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/factory/PantheonNodeFactory.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/transaction/PantheonWeb3j.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/transaction/Transactions.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/transaction/account/TransferTransaction.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/transaction/eth/EthGetTransactionCountTransaction.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/transaction/eth/EthSendRawTransactionTransaction.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/transaction/eth/EthTransactions.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/transaction/perm/PermAddAccountsToWhitelistTransaction.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/transaction/perm/PermGetAccountsWhitelistTransaction.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/transaction/perm/PermRemoveAccountsFromWhitelistTransaction.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/permissioning/AccountsWhitelistAcceptanceTest.java
  ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/core/TransactionPool.java
  ethereum/core/src/test/java/tech/pegasys/pantheon/ethereum/core/TransactionPoolTest.java
  ethereum/jsonrpc/build.gradle
  ethereum/jsonrpc/src/integration-test/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcTestMethodsFactory.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcErrorConverter.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcMethodsFactory.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/RpcApis.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermAddAccountsToWhitelist.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermGetAccountsWhitelist.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermRemoveAccountsFromWhitelist.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/response/JsonRpcError.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/AbstractEthJsonRpcHttpServiceTest.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpServiceHostWhitelistTest.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpServiceRpcApisTest.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpServiceTest.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/EthSendRawTransactionTest.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermAddAccountsToWhitelistTest.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermGetAccountsWhitelistTest.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermRemoveAccountsFromWhitelistTest.java
  ethereum/permissioning/build.gradle
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/AccountWhitelistController.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/AccountWhitelistControllerTest.java
  pantheon/src/main/java/tech/pegasys/pantheon/RunnerBuilder.java
Labels: permissioning

#430 NC-2013 devp2p whitelist
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/netty/NettyP2PNetwork.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/permissioning/NodeWhitelistController.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/NettyP2PNetworkTest.java
Labels: permissioning

#532 #508 - Added CLI ref and Debugging conceptual content for metrics
  docs/Reference/Pantheon-CLI-Syntax.md
  docs/Using-Pantheon/Debugging.md
Labels: needs engineering approval

#536 Azure quickstart tutorial
  docs/Getting-Started/Private-Network-Quickstart.md
  docs/Getting-Started/azure/Azure-Private-Network-Quickstart.md
  docs/Getting-Started/azure/alethio-light-explorer-screenshot.png
  docs/Getting-Started/azure/create-resource-button-screenshot.png
  docs/Getting-Started/azure/deployment-complete-screenshot.png
Labels: documentation

#545 Quick fix of doc path URL
  mkdocs.yml
Labels: bug, documentation

#533 Events, logs, and accessing logs content
  docs/Reference/JSON-RPC-API-Methods.md
  docs/Reference/JSON-RPC-API-Objects.md
  docs/Using-Pantheon/Accessing-Logs-Using-JSON-RPC.md
  docs/Using-Pantheon/Events-and-Logs.md
  docs/Using-Pantheon/FilterExample.md
  docs/Using-Pantheon/Filters.md
  docs/Using-Pantheon/RPC-PubSub.md
  docs/Using-Pantheon/Switching from Geth.md
  mkdocs.yml
Labels: documentation

#618 CLI options and commands renaming
  docs/Reference/Pantheon-CLI-Syntax.md
  pantheon/src/main/java/tech/pegasys/pantheon/cli/BlocksSubCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/DefaultCommandValues.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/ExportPublicKeySubCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/ImportSubCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/NetworkName.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PublicKeySubCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/StandaloneCommand.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/BlockSubCommandTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/ExportPublicKeySubCommandTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/ImportSubCommandTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PublicKeySubCommandTest.java
  pantheon/src/test/resources/complete_config.toml
  pantheon/src/test/resources/everything_config.toml
Labels: api, documentation, needs engineering approval

#593 fixes #522 remove mention of gas setting from eth_estimateGas
  docs/Reference/JSON-RPC-API-Methods.md
  docs/Reference/JSON-RPC-API-Objects.md
Labels: documentation

#585 fixes #448 updates for new pantheon-quickstart repo and shell scripts
  docs/Getting-Started/Getting-Started.md
  docs/Getting-Started/Private-Network-Quickstart.md
  docs/Getting-Started/azure/Azure-Private-Network-Quickstart.md
  docs/Installation/Build-From-Source.md
  docs/Tutorials/Create-Private-Network.md
  docs/Tutorials/Private-Network-Quickstart.md
  docs/Using-Pantheon/Transactions.md
  mkdocs.yml
Labels: documentation

#645 Nc 2026 network option
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/ThreadPantheonNodeRunner.java
  docs/Configuring-Pantheon/Accounts-for-Testing.md
  docs/Configuring-Pantheon/Logging.md
  docs/Configuring-Pantheon/NetworkID-And-ChainID.md
  docs/Configuring-Pantheon/Networking.md
  docs/Configuring-Pantheon/Passing-JVM-Options.md
  docs/Configuring-Pantheon/Testing-Developing-Nodes.md
  docs/Configuring-Pantheon/Using-Configuration-File.md
  docs/Consensus-Protocols/Clique.md
  docs/Consensus-Protocols/IBFT.md
  docs/Getting-Started/Run-Docker-Image.md
  docs/Getting-Started/Starting-Pantheon.md
  docs/Reference/JSON-RPC-API-Methods.md
  docs/Reference/Pantheon-CLI-Syntax.md
  docs/Reference/Using-JSON-RPC-API.md
  docs/Tutorials/Create-Private-Network.md
  docs/Using-Pantheon/Debugging.md
  pantheon/src/main/java/tech/pegasys/pantheon/cli/DefaultCommandValues.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/EthNetworkConfig.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/NetworkName.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/StandaloneCommand.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/resources/complete_config.toml
  pantheon/src/test/resources/everything_config.toml
Labels: api, documentation

#661 NC-2120 --discovery-enabled option refactoring
  docs/Configuring-Pantheon/Networking.md
  docs/Reference/Pantheon-CLI-Syntax.md
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/resources/complete_config.toml
  pantheon/src/test/resources/everything_config.toml
Labels: api, documentation

#654 Added p2p enabled
  docs/Reference/Pantheon-CLI-Syntax.md
Labels: documentation

#667 IBFT available in v1.0 note added
  docs/Configuring-Pantheon/IBFT.md
  docs/Consensus-Protocols/Comparing-PoA.md
  docs/Consensus-Protocols/IBFT.md
  docs/Consensus-Protocols/Overview-Consensus.md
  docs/Reference/JSON-RPC-API-Methods.md
  docs/Reference/Using-JSON-RPC-API.md
Labels: documentation

#666 Updated to reflect CLIQUE and IBFT methods no longer enabled by default
  docs/Consensus-Protocols/Clique.md
  docs/Consensus-Protocols/IBFT.md
  docs/Reference/JSON-RPC-API-Methods.md
  docs/Reference/Using-JSON-RPC-API.md
Labels: documentation

#668 Updated MetaMask note
  docs/Reference/Pantheon-CLI-Syntax.md
Labels: documentation

#680 NC-2206 Remove-- max-trailing-peers option
  docs/Configuring-Pantheon/Networking.md
  docs/Reference/Pantheon-CLI-Syntax.md
  pantheon/src/main/java/tech/pegasys/pantheon/cli/DefaultCommandValues.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/resources/everything_config.toml
Labels: api, documentation

#679 NC-1737 Enabled warning on CLI dependent options
  pantheon/src/main/java/tech/pegasys/pantheon/Pantheon.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/CommandLineUtils.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/util/StringUtils.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandLineUtilsTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/util/StringUtilsTest.java
Labels: api

#675 Added libsodium requirement
  CONTRIBUTING.md
Labels: documentation

#639 A few additions and fixes to the Consensus Mechanisms documentation page
  docs/Consensus-Protocols/Consensus-Mechanisms.md
Labels: documentation

#669 Added privacy CLI options
  docs/Reference/Pantheon-CLI-Syntax.md
Labels: documentation

#687 Added metrics options for running from Docker image
  docs/Getting-Started/Run-Docker-Image.md
Labels: needs engineering approval

#674 Added options for metrics push mode
  docs/Reference/Pantheon-CLI-Syntax.md
  docs/Using-Pantheon/Debugging.md
Labels: needs engineering approval

#705 Updated Permissions CLI options
  docs/Reference/Pantheon-CLI-Syntax.md
Labels: needs engineering approval

#711 fixed key export subcommand option was --from instead of --to
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PublicKeySubCommand.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PublicKeySubCommandTest.java
Labels: api, bug
