Repository PegaSysEng/pantheon, pull requests merged in 2019-02, with the labels that each got.

#766 [NC-2247] Fixing node whitelist isPermitted check
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerDiscoveryController.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/permissioning/NodeWhitelistController.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/permissioning/NodeWhitelistControllerTest.java
Labels: permissioning

#776 NC-2250 multiple name options only search for the longest one
  pantheon/src/main/java/tech/pegasys/pantheon/cli/TomlConfigFileDefaultProvider.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/TomlConfigFileDefaultProviderTest.java
  pantheon/src/test/resources/complete_config.toml
  pantheon/src/test/resources/everything_config.toml
Labels: bug

#783 Permissioning API methods
  docs/Configuring-Pantheon/Bootnodes.md
  docs/Configuring-Pantheon/Node-Keys.md
  docs/Reference/JSON-RPC-API-Methods.md
  docs/Tutorials/Create-Private-Network.md
Labels: documentation

#771 Clique private network
  docs/Consensus-Protocols/Clique.md
  docs/Tutorials/Create-Private-Clique-Network.md
  docs/Tutorials/Create-Private-Network.md
  docs/global/test_accounts.md
  mkdocs.yml
Labels: documentation

#834 [NC-2118] Method to reload permissions file
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcMethodsFactory.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermReloadPermissionsFromFile.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/response/JsonRpcError.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermReloadPermissionsFromFileTest.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/NoopP2PNetwork.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/permissioning/NodeWhitelistController.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/permissioning/NodeWhitelistControllerTest.java
  ethereum/permissioning/build.gradle
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/AccountWhitelistController.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/PermissioningConfigurationBuilder.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/TomlConfigFileParser.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/AccountWhitelistControllerTest.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/PermissioningConfigurationBuilderTest.java
  ethereum/permissioning/src/test/resources/permissioning_config.toml
  ethereum/permissioning/src/test/resources/permissioning_config_absent_whitelists.toml
  ethereum/permissioning/src/test/resources/permissioning_config_account_whitelist_only.toml
  ethereum/permissioning/src/test/resources/permissioning_config_empty_whitelists.toml
  ethereum/permissioning/src/test/resources/permissioning_config_invalid_account.toml
  ethereum/permissioning/src/test/resources/permissioning_config_invalid_enode.toml
  ethereum/permissioning/src/test/resources/permissioning_config_node_whitelist_only.toml
  ethereum/permissioning/src/test/resources/permissioning_config_node_whitelist_only_multiline.toml
  ethereum/permissioning/src/test/resources/permissioning_config_unrecognized_key.toml
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/custom/EnodeToURIPropertyConverter.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/custom/EnodeToURIPropertyConverterTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/util/PermissioningConfigurationValidatorTest.java
  util/src/main/java/tech/pegasys/pantheon/util/enode/EnodeURL.java
  util/src/test/java/tech/pegasys/pantheon/util/enode/EnodeURLTest.java
Labels: permissioning

#815 [NC-2046] JWT authentication for JSON-RPC
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/condition/login/AwaitLoginResponse.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/condition/net/ExpectNetVersionPermissionException.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/httptransaction/HttpRequestFactory.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/httptransaction/LoginResponds.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/jsonrpc/Login.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/jsonrpc/Net.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/NodeConfiguration.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/PantheonNode.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/transaction/net/NetVersionTransaction.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/jsonrpc/HttpServiceLoginAcceptanceTest.java
  acceptance-tests/src/test/resources/authentication/auth.toml
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpService.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/JsonRpcMethod.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/response/JsonRpcError.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpServiceLoginTest.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/NetListeningTest.java
  ethereum/jsonrpc/src/test/resources/JsonRpcHttpService/auth.toml
Labels: documentation

#865 Renaming authentication config file cli command
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/resources/everything_config.toml
Labels: permissioning

#877 [PAN-2239] Disconnect peer removed from node whitelist
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/permissioning/NodesWhitelistAcceptanceTest.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/PeerDiscoveryAgent.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/Bucket.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/DiscoveryProtocolLogger.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerDiscoveryController.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerTable.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/netty/NettyP2PNetwork.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/PeerDiscoveryTimestampsTest.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerDiscoveryControllerTest.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerDiscoveryTableRefreshTest.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerTableTest.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/NodeWhitelistController.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/node/NodeWhitelistUpdatedEvent.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/NodeWhitelistControllerTest.java
Labels: permissioning

#912 [PAN-2117] Error when removing bootnodes from nodes whitelist
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/NodeConfiguration.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/PantheonNode.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/cluster/Cluster.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/factory/PantheonFactoryConfiguration.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/factory/PantheonFactoryConfigurationBuilder.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/factory/PantheonNodeFactory.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/permissioning/NodesWhitelistAcceptanceTest.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermRemoveNodesFromWhitelist.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/response/JsonRpcError.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermRemoveNodesFromWhitelistTest.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/NettyP2PNetworkTest.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerDiscoveryControllerTest.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/RecursivePeerRefreshStateTest.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/NodeWhitelistController.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/WhitelistOperationResult.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/NodeWhitelistControllerTest.java
  pantheon/src/main/java/tech/pegasys/pantheon/RunnerBuilder.java
Labels: permissioning

#921 [MINOR] consistency in help messages
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/StandaloneCommand.java
Labels: documentation, enhancement

#924 [MINOR] removed shoulds
  CODING-CONVENTIONS.md
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
Labels: documentation

#923 Updates for CLI options use with Docker image
  docs/Getting-Started/Run-Docker-Image.md
  docs/Reference/Pantheon-CLI-Syntax.md
  mkdocs.yml
Labels: needs engineering approval

#888 Add public key address export subcommand
  docs/Reference/Pantheon-CLI-Syntax.md
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PublicKeySubCommand.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PublicKeySubCommandTest.java
Labels: api, documentation, enhancement

#910 404 page style
  docs/custom_theme/404.html
Labels: bug, documentation

#947 Added future message configuration options
  docs/Consensus-Protocols/IBFT.md
Labels: needs engineering approval

#953 Added note that changes to permissions configuration file persist across restarts
  docs/Permissions/Permissioning.md
Labels: needs engineering approval

#944 RLP encode subcommand
  docs/Reference/Pantheon-CLI-Syntax.md
  pantheon/src/main/java/tech/pegasys/pantheon/Pantheon.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/DefaultCommandValues.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/rlp/IbftExtraDataCLIAdapter.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/rlp/JSONToRLP.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/rlp/RLPSubCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/rlp/RLPType.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/rlp/RLPSubCommandTest.java
Labels: api

#948 Added Create an IBFT 2.0 network tutorial
  docs/Consensus-Protocols/IBFT.md
  docs/Reference/Pantheon-CLI-Syntax.md
  docs/Tutorials/Create-IBFT-Network.md
  mkdocs.yml
Labels: needs engineering approval

#968 Updated Clique and IBFT 2.0 docs to include complete genesis file
  docs/Consensus-Protocols/Clique.md
  docs/Consensus-Protocols/IBFT.md
Labels: needs engineering approval
