Repository PegaSysEng/pantheon, pull requests merged in 2019-07, with the labels that each got.

#1622 [PIE-1736] Implement incoming transaction messages CLI option as an unstable command.
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionPoolConfiguration.java
  pantheon/src/main/java/tech/pegasys/pantheon/Pantheon.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/resources/everything_config.toml
Labels: api, bug, doc next release

#1626 [PIE-1737] Simplify PantheonCommand `run` and `parse` methods.
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
Labels: refactoring

#1627 [PIE-1741] Refactor CLI
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/ThreadPantheonNodeRunner.java
  pantheon/src/main/java/tech/pegasys/pantheon/RunnerBuilder.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/config/EthNetworkConfig.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/config/NetworkName.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/error/PantheonExceptionHandler.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/subcommands/PasswordSubCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/subcommands/PublicKeySubCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/subcommands/blocks/BlocksSubCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/subcommands/operator/OperatorSubCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/subcommands/rlp/IbftExtraDataCLIAdapter.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/subcommands/rlp/JSONToRLP.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/subcommands/rlp/RLPSubCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/subcommands/rlp/RLPType.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/util/CascadingDefaultProvider.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/util/CommandLineUtils.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/util/ConfigOptionSearchAndRunHandler.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/util/EnvironmentVariableDefaultProvider.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/util/TomlConfigFileDefaultProvider.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/util/VersionProvider.java
  pantheon/src/main/java/tech/pegasys/pantheon/controller/PantheonController.java
  pantheon/src/test/java/tech/pegasys/pantheon/RunnerTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandLineUtilsTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/ConfigOptionSearchAndRunHandlerTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/EnvironmentVariableDefaultProviderTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/TomlConfigFileDefaultProviderTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/operator/OperatorSubCommandTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/util/LocalPermissioningConfigurationValidatorTest.java
Labels: refactoring

#1628 [PAN-2703] JSON-RPC api net_services should display the actual ports
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/condition/net/ExpectNetServicesReturnsAllServicesAsActive.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/condition/net/ExpectNetServicesReturnsOnlyJsonRpcActive.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpService.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/websocket/WebSocketService.java
Labels: api, bug

#1645 Display World State Sync Progress in Logs
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/worldstate/CompleteTaskStep.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/worldstate/WorldStateDownloader.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/sync/worldstate/CompleteTaskStepTest.java
  metrics/core/src/main/java/tech/pegasys/pantheon/metrics/RunnableCounter.java
Labels: enhancement

#1653 [PAN-2871] Intermittent Test Failures in TransactionsMessageSenderTest
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionsMessageSenderTest.java
Labels: bug, testing

#1662 [PAN-2853] Create a metric tracking DB size
  services/kvstore/build.gradle
  services/kvstore/src/main/java/tech/pegasys/pantheon/services/kvstore/RocksDbKeyValueStorage.java
  services/kvstore/src/test/java/tech/pegasys/pantheon/services/kvstore/RocksDbKeyValueStorageTest.java
Labels: enhancement, performance

#1663 Factorise metrics code for KeyValueStorage database
  services/kvstore/src/main/java/tech/pegasys/pantheon/services/kvstore/ColumnarRocksDbKeyValueStorage.java
  services/kvstore/src/main/java/tech/pegasys/pantheon/services/kvstore/RocksDBMetricsHelper.java
  services/kvstore/src/main/java/tech/pegasys/pantheon/services/kvstore/RocksDbKeyValueStorage.java
Labels: refactoring

#1665 [PAN-1683] Limit the fraction of wire connections initiated by peers
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/PantheonNode.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/ThreadPantheonNodeRunner.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/configuration/PantheonFactoryConfigurationBuilder.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/transactions/TestNode.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/config/RlpxConfiguration.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/rlpx/RlpxAgent.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/rlpx/RlpxAgentTest.java
  pantheon/src/main/java/tech/pegasys/pantheon/RunnerBuilder.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/DefaultCommandValues.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/test/java/tech/pegasys/pantheon/RunnerTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/resources/everything_config.toml
  util/src/main/java/tech/pegasys/pantheon/util/number/Fraction.java
Labels: enhancement, security

#1684 Enclave refactoring
  enclave/build.gradle
  enclave/src/integration-test/java/tech/pegasys/pantheon/enclave/EnclaveTest.java
  enclave/src/main/java/tech/pegasys/pantheon/enclave/Enclave.java
Labels: api, testing

#1595 update for quickstart 1.1.3 including Prometheus and Grafana
  docs/Tutorials/Private-Network-Quickstart.md
  docs/Tutorials/grafana.png
Labels: documentation

#1719 [PAN-2725] Accounts Permissioning Acceptance Tests - OnChain+Local Config
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/permissioning/AccountLocalAndOnChainPermissioningAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/permissioning/AccountSmartContractPermissioningAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/permissioning/AccountSmartContractPermissioningAcceptanceTestBase.java
Labels: acceptance test, permissioning

#1735 [PAN-2724] - Permissioning Acceptance Test - Local & OnChain Nodes
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/permissioning/NodeLocalAndOnChainPermissioningAcceptanceTest.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/permissioning/NodeSmartContractPermissioningAcceptanceTestBase.java
Labels: acceptance test, permissioning

#1763 Fixes PIE-1669 typo
  docs/Consensus-Protocols/IBFT.md
Labels: documentation

#1759 [PAN-2727] Permissioning Acceptance Test - Verify OnChain Nodes Out of Sync
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/permissioning/NodeSmartContractPermissioningOutOfSyncAcceptanceTest.java
Labels: acceptance test, permissioning

#1742 fix list typo (missing new line)
  docs/Reference/Pantheon-API-Methods.md
Labels: documentation

#1779 fix documentation formatting
  docs/Permissions/Onchain-Permissioning/Getting-Started-Onchain-Permissioning.md
  docs/Reference/Pantheon-API-Methods.md
Labels: documentation
