Repository PegaSysEng/pantheon, pull requests merged in 2019-05, with the labels that each got.

#1374 update python mkdocs requirements versions
  docs/custom_theme/assets/javascripts/application.c6f2d7d2.js
  docs/custom_theme/main.html
  docs/requirements.txt
Labels: documentation

#1390 Remove hotjar tag
  docs/custom_theme/main.html
  mkdocs.yml
Labels: documentation

#1399 Fix non-deterministic test caused by variable size of generated transactions
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/messages/LimitedTransactionsMessagesTest.java
Labels: bug

#1406 PAN-2449: Remove NodePermissioningLocalConfig external references
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/PeerDiscoveryAgent.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/VertxPeerDiscoveryAgent.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerDiscoveryController.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/network/DefaultP2PNetwork.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/PeerDiscoveryTestHelper.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/PeerDiscoveryTimestampsTest.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/MockPeerDiscoveryAgent.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerDiscoveryControllerTest.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerDiscoveryTableRefreshTest.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/network/P2PNetworkTest.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/node/NodePermissioningController.java
  pantheon/src/main/java/tech/pegasys/pantheon/RunnerBuilder.java
Labels: permissioning

#1414 Updated block size limit configuration
  docs/Configuring-Pantheon/FreeGas.md
Labels: needs engineering approval

#1405 Troubleshooting doc
  docs/Configuring-Pantheon/Networking/Configuring-Ports.md
  docs/Reference/Pantheon-CLI-Syntax.md
  docs/Troubleshooting/Troubleshooting.md
  docs/Using-Pantheon/Monitoring.md
  mkdocs.yml
Labels: needs engineering approval

#1438 Allow config files to specify no bootnodes
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/resources/no_bootnodes.toml
Labels: api, bug

#1439 Decode devp2p packets off the event thread
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/VertxPeerDiscoveryAgent.java
Labels: performance

#1425 Add placeholders system to have global variables in markdown
  docs/Configuring-Pantheon/Logging.md
  docs/Configuring-Pantheon/Passing-JVM-Options.md
  docs/Getting-Started/Run-Docker-Image.md
  docs/GettingStartedBinaries.md
  docs/Installation/Build-From-Source.md
  docs/Installation/Install-Binaries.md
  docs/Pantheon-API/Authentication.md
  docs/Reference/Pantheon-API-Methods.md
  docs/Reference/Pantheon-CLI-Syntax.md
  docs/Tutorials/Private-Network-Quickstart.md
  docs/Using-Pantheon/Transactions/Transactions.md
  docs/requirements.txt
  mkdocs.yml
Labels: documentation, enhancement

#1453 add RTD config file to fix Python version issue
  Jenkinsfile
  readthedocs.yml
Labels: bug, documentation

#1451 add doc build badge to readme
  README.md
Labels: documentation

#1454 warning banner when using latest version
  docs/custom_theme/assets/javascripts/pantheon_custom.js
  docs/custom_theme/assets/stylesheets/pantheon_custom.css
  docs/custom_theme/main.html
  mkdocs.yml
Labels: documentation, enhancement

#1476 make CLI options names with hyphen-minus searchable and reduce index size
  mkdocs.yml
Labels: bug, documentation, enhancement

#1469 update doc for python version
  MKDOCS-MARKDOWN-GUIDE.md
Labels: documentation

#1497 Updated an incorrect command.
  docs/Tutorials/Private-Network-Quickstart.md
Labels: documentation

#1501 Simplify text
  docs/Permissions/Permissioning-Overview.md
Labels: documentation
