Repository PegaSysEng/pantheon, pull requests merged in 2019-04, with the labels that each got.

#1187 Added droppedPendingTransactions subscription
  docs/Using-Pantheon/RPC-PubSub.md
  docs/Using-Pantheon/Transactions/Transaction-Pool.md
Labels: needs engineering approval

#1198 Update running-developer-builds.md
  docs/development/running-developer-builds.md
Labels: bug, documentation

#1195 Added content on using Truffle with Pantheon
  docs/Using-Pantheon/Truffle.md
  mkdocs.yml
Labels: documentation

#1199 Doc CI pipeline for build and tests
  Jenkinsfile
Labels: documentation

#1204 add link to issues system to the doc site footer
  docs/custom_theme/partials/footer.html
  mkdocs.yml
Labels: documentation

#1182 Added eea_* methods
  docs/Reference/JSON-RPC-API-Methods.md
  docs/Reference/JSON-RPC-API-Objects.md
Labels: documentation, needs engineering approval

#1201 Privacy overview and transaction processing
  docs/Privacy/Privacy.md
  docs/images/PrivateTransactionProcessing.png
Labels: needs engineering approval

#1218 [PAN-2265] Expose fast-sync options on command line
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/SynchronizerConfiguration.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/sync/fastsync/FastSyncActions.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/sync/fastsync/FastSyncActionsTest.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/DefaultCommandValues.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/resources/complete_config.toml
  pantheon/src/test/resources/everything_config.toml
Labels: api

#1220 switch GA tag to Google tag manager
  docs/custom_theme/main.html
  mkdocs.yml
Labels: documentation

#1225 hotjar tag for feedback (and more)
  docs/custom_theme/assets/javascripts/application.c6f2d7d2.js
  docs/custom_theme/main.html
  docs/requirements.txt
  mkdocs.yml
Labels: documentation

#1258 [PAN-2499] debug trace transaction
  ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/core/Transaction.java
  ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/debug/TraceFrame.java
  ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/vm/DebugOperationTracer.java
  ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/vm/MessageFrame.java
  ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/vm/operations/RevertOperation.java
  ethereum/core/src/test/java/tech/pegasys/pantheon/ethereum/vm/operations/RevertOperationTest.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/DebugTraceTransaction.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/response/JsonRpcError.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/results/StructLog.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/DebugTraceTransactionTest.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
Labels: WIP, api, enhancement, evm, work in progress

#1270 Expose sync mode option
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
Labels: api

#1272 Feature/move subclass in pantheon command
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/converter/RpcApisConverter.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/converter/exception/RpcApisConversionException.java
Labels: refactoring

#1271 Implement max message size rather than limiting with fixed number of transactions
  ethereum/core/src/test-support/java/tech/pegasys/pantheon/ethereum/core/BlockDataGenerator.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/messages/LimitedTransactionsMessages.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/messages/TransactionsMessage.java
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionsMessageSender.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/messages/LimitedTransactionsMessagesTest.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/transactions/TransactionsMessageSenderTest.java
  ethereum/rlp/src/main/java/tech/pegasys/pantheon/ethereum/rlp/AbstractRLPOutput.java
Labels: enhancement, performance

#1315 PIE-1526: Fix account permissioning check case matching
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/AccountWhitelistController.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/AccountWhitelistControllerTest.java
Labels: permissioning

#1314 PIE-1526: Fix account permissioning check case matching
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/AccountWhitelistController.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/AccountWhitelistControllerTest.java
Labels: permissioning

#1317 Update Enclave executePost method
  enclave/src/main/java/tech/pegasys/pantheon/enclave/Enclave.java
Labels: bug, invalid, performance

#1321 PIE-1526: Normalize account permissioning addresses in whitelist
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/AccountWhitelistController.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/AccountWhitelistControllerTest.java
Labels: permissioning

#1320 PIE-1526: Normalize account permissioning addresses in whitelist
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/AccountWhitelistController.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/AccountWhitelistControllerTest.java
Labels: permissioning

#1328 [PAN-1878] Provide error message when invalid key specified in key file
  pantheon/src/main/java/tech/pegasys/pantheon/controller/KeyPairUtil.java
  pantheon/src/test/java/tech/pegasys/pantheon/util/KeyPairUtilTest.java
  pantheon/src/test/resources/invalidPrivateKey.txt
  pantheon/src/test/resources/validPrivateKey.txt
Labels: api

#1327 [PAN-2576] Allow whitespace in path
  crypto/src/test/java/tech/pegasys/pantheon/crypto/SECP256K1Test.java
Labels: bug

#1329 [PIE-1531] Allow whitespace in file paths loaded from resources directory
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/factory/PantheonNodeFactory.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/factory/PermissionedNodeBuilder.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/permissioning/SmartContractNodePermissioningAcceptanceTestBase.java
  config/src/main/java/tech/pegasys/pantheon/config/GenesisConfigFile.java
  ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/mainnet/MainnetProtocolSpecs.java
  ethereum/core/src/test/java/tech/pegasys/pantheon/ethereum/mainnet/MainnetProtocolScheduleTest.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/ethtaskutils/BlockchainSetupUtil.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/messages/BlockBodiesMessageTest.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/messages/BlockHeadersMessageTest.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/messages/GetBlockBodiesMessageTest.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/messages/NewBlockHashesMessageTest.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/LocalPermissioningConfigurationBuilderTest.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/SmartContractPermissioningControllerTest.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/EthNetworkConfig.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/custom/RpcAuthFileValidatorTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/util/BlockImporterTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/util/LocalPermissioningConfigurationValidatorTest.java
  testutil/src/main/java/tech/pegasys/pantheon/testutil/BlockTestUtil.java
Labels: bug

#1332 [PAN-2574] Fix failed tests on Windows
  ethereum/eth/src/main/java/tech/pegasys/pantheon/ethereum/eth/manager/task/AbstractEthTask.java
  ethereum/eth/src/test/java/tech/pegasys/pantheon/ethereum/eth/manager/task/AbstractEthTaskTest.java
Labels: bug, testing, windows

#1341 Remove unstable fast sync note in documentation
  docs/Reference/Pantheon-CLI-Syntax.md
Labels: documentation

#1354 Added txpool_pantheonStatistics
  docs/Reference/JSON-RPC-API-Methods.md
Labels: needs engineering approval
