Repository PegaSysEng/pantheon, pull requests merged in 2019-03, with the labels that each got.

#796 Update doc contribution guidelines
  CONTRIBUTING.md
  DOC-STYLE-GUIDE.md
  MKDOCS-MARKDOWN-GUIDE.md
  docs/custom_theme/main.html
  mkdocs.yml
Labels: documentation, enhancement, work in progress

#1042 Added metrics-category CLI option
  docs/Reference/Pantheon-CLI-Syntax.md
  docs/Using-Pantheon/Debugging.md
Labels: needs engineering approval

#1039 [PAN-2342] Update discovery logic to trust bootnodes only when out of sync
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerDiscoveryController.java
  ethereum/permissioning/build.gradle
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/node/NodePermissioningController.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/node/NodePermissioningProvider.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/node/provider/SyncStatusNodePermissioningProvider.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/node/NodePermissioningControllerTest.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/node/provider/SyncStatusNodePermissioningProviderTest.java
Labels: permissioning

#1050 remove 404 custom page as it doesn't work with RTD and MkDocs for now
  docs/custom_theme/404.html
Labels: bug, documentation

#1049 Remove DB init need to use public key subcommand
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PublicKeySubCommand.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PublicKeySubCommandTest.java
Labels: enhancement

#1041 Added info on block time and timeout settings for IBFT 2.0
  docs/Consensus-Protocols/IBFT.md
Labels: needs engineering approval

#1062 Enable the edit link again on doc site to ease external doc contributions.
  mkdocs.yml
Labels: documentation

#1074 [PAN-2343] smart contract permission controller stub
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/SmartContractPermissioningController.java
Labels: WIP

#1069 workaround for 404 error pages assets and sitemap links
  .gitignore
  docs/custom_theme/404.html
  docs/custom_theme/partials/footer.html
  docs/requirements.txt
  mkdocs.yml
Labels: documentation

#1076 Added section on using Geth attach with Pantheon
  docs/JSON-RPC-API/Using-JSON-RPC-API.md
  docs/Reference/JSON-RPC-API-Methods.md
Labels: needs engineering approval

#1084 enable copy button in code blocks
  MKDOCS-MARKDOWN-GUIDE.md
  mkdocs.yml
Labels: documentation

#1071 [PAN-2348] Changes in chain head should trigger new permissioning check for active peers
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/netty/NettyP2PNetwork.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/NettyP2PNetworkTest.java
Labels: permissioning

#1081 Added IBFT 1.0
  docs/Consensus-Protocols/IBFT.md
  docs/Consensus-Protocols/Overview-Consensus.md
  docs/Consensus-Protocols/QuorumIBFT.md
  mkdocs.yml
Labels: needs engineering approval

#1083 [PAN-2343] smart contract permission controller
  ethereum/core/src/main/java/tech/pegasys/pantheon/ethereum/transaction/TransactionSimulator.java
  ethereum/permissioning/build.gradle
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/SmartContractPermissioningController.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/SmartContractPermissioningControllerTest.java
  ethereum/permissioning/src/test/resources/SmartContractPermissioningControllerTest/preseededSmartPermissioning.json
Labels: permissioning

#1075 [PAN-2345] node permissioning controller
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/PantheonNode.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/factory/PantheonFactoryConfiguration.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/factory/PantheonFactoryConfigurationBuilder.java
  acceptance-tests/src/test/java/tech/pegasys/pantheon/tests/acceptance/dsl/node/factory/PantheonNodeFactory.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermAddNodesToWhitelist.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermReloadPermissionsFromFile.java
  ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermRemoveNodesFromWhitelist.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermAddNodesToWhitelistTest.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermGetNodesWhitelistTest.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermReloadPermissionsFromFileTest.java
  ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/permissioning/PermRemoveNodesFromWhitelistTest.java
  ethereum/mock-p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/testing/MockNetwork.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/NoopP2PNetwork.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/api/P2PNetwork.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/PeerDiscoveryAgent.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/VertxPeerDiscoveryAgent.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerDiscoveryController.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/RecursivePeerRefreshState.java
  ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/netty/NettyP2PNetwork.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/NettyP2PNetworkTest.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/PeerDiscoveryTestHelper.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/MockPeerDiscoveryAgent.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerDiscoveryControllerTest.java
  ethereum/p2p/src/test/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/RecursivePeerRefreshStateTest.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/AccountWhitelistController.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/LocalPermissioningConfiguration.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/NodeLocalConfigPermissioningController.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/NodePermissioningControllerFactory.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/PermissioningConfiguration.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/PermissioningConfigurationBuilder.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/SmartContractPermissioningConfiguration.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/WhitelistOperationResult.java
  ethereum/permissioning/src/main/java/tech/pegasys/pantheon/ethereum/permissioning/node/NodePermissioningController.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/AccountWhitelistControllerTest.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/LocalPermissioningConfigurationBuilderTest.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/LocalPermissioningConfigurationTest.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/NodeLocalConfigPermissioningControllerTest.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/node/NodePermissioningControllerFactoryTest.java
  ethereum/permissioning/src/test/java/tech/pegasys/pantheon/ethereum/permissioning/node/NodePermissioningControllerTest.java
  pantheon/src/main/java/tech/pegasys/pantheon/RunnerBuilder.java
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/main/java/tech/pegasys/pantheon/util/PermissioningConfigurationValidator.java
  pantheon/src/test/java/tech/pegasys/pantheon/RunnerTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/CommandTestAbstract.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/util/LocalPermissioningConfigurationValidatorTest.java
Labels: permissioning

#1092 Better bootnodes option error message
  pantheon/src/main/java/tech/pegasys/pantheon/cli/PantheonCommand.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/PantheonCommandTest.java
  pantheon/src/test/java/tech/pegasys/pantheon/cli/custom/EnodeToURIPropertyConverterTest.java
Labels: api, bug

#1145 Added txpool_pantheonTransactions
  docs/JSON-RPC-API/Using-JSON-RPC-API.md
  docs/Reference/JSON-RPC-API-Methods.md
  docs/Reference/Pantheon-CLI-Syntax.md
Labels: needs engineering approval

#1103 Minor improvement to Private Network Quickstart doc
  docs/Tutorials/Private-Network-Quickstart.md
Labels: documentation, enhancement

#1061 Add EthStats docs
  docs/EthStats/Lite-Block-Explorer.md
  docs/EthStats/Lite-Network-Health-Monitor.md
  docs/EthStats/Overview.md
  mkdocs.yml
Labels: documentation, work in progress

#1138 Added txpoolmaxsize
  docs/Reference/JSON-RPC-API-Methods.md
  docs/Reference/Pantheon-CLI-Syntax.md
  docs/Tutorials/Create-Private-Network.md
  docs/Using-Pantheon/Account-Management.md
  docs/Using-Pantheon/Transactions/Transaction-Pool.md
  docs/Using-Pantheon/Transactions/Transactions.md
  mkdocs.yml
Labels: needs engineering approval

#1124 Azure one click tutorial
  docs/Getting-Started/azure/Azure-Private-Network-Quickstart.md
  docs/Getting-Started/azure/create-resource-button-screenshot.png
  docs/Tutorials/Azure/Azure-Private-Network-Quickstart.md
  docs/Tutorials/Azure/alethio-light-explorer-screenshot.png
  docs/Tutorials/Azure/create-resource-button-screenshot.png
  docs/Tutorials/Azure/deployment-complete-screenshot.png
  mkdocs.yml
Labels: documentation

#1157 fix azure deploy url
  docs/Tutorials/Azure/Azure-Private-Network-Quickstart.md
Labels: bug, documentation

#1149 Updated tutorials for printing of enode on startup
  docs/Configuring-Pantheon/Node-Keys.md
  docs/Reference/JSON-RPC-API-Methods.md
  docs/Reference/Pantheon-CLI-Syntax.md
  docs/Tutorials/Create-IBFT-Network.md
  docs/Tutorials/Create-Permissioned-Network.md
  docs/Tutorials/Create-Private-Clique-Network.md
  docs/Tutorials/Create-Private-Network.md
  docs/images/EnodeStartup.png
Labels: needs engineering approval

#1141 Added static nodes doc
  docs/Configuring-Pantheon/Networking.md
  docs/Configuring-Pantheon/Networking/Bootnodes.md
  docs/Configuring-Pantheon/Networking/Configuring-Ports.md
  docs/Configuring-Pantheon/Networking/Managing-Peers.md
  docs/JSON-RPC-API/Using-JSON-RPC-API.md
  docs/Reference/JSON-RPC-API-Methods.md
  docs/Reference/Pantheon-CLI-Syntax.md
  mkdocs.yml
Labels: needs engineering approval

#1091 [PRIV-26] Privacy documentation
  docs/Privacy/Privacy.md
  docs/Privacy/Start-Pantheon-Privacy.md
  docs/Reference/JSON-RPC-API-Methods.md
  docs/Reference/JSON-RPC-API-Objects.md
Labels: documentation, work in progress
